// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD4GqgQwr5apr3m4P_w19BBQUV4qGoTEVc',
    appId: '1:322358613164:web:be62a0d143c00afdd7bb09',
    messagingSenderId: '322358613164',
    projectId: 'lakwatsa-bbriones-app',
    authDomain: 'lakwatsa-bbriones-app.firebaseapp.com',
    storageBucket: 'lakwatsa-bbriones-app.firebasestorage.app',
    measurementId: 'G-971K403ED6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFAXRK7hRRwxLDQB1tTM4ibliB19NYGZI',
    appId: '1:322358613164:android:e76eed0122f7fe59d7bb09',
    messagingSenderId: '322358613164',
    projectId: 'lakwatsa-bbriones-app',
    storageBucket: 'lakwatsa-bbriones-app.firebasestorage.app',
  );
}
